package com.ai_health.assistant.data.cache

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a cached health data entry in the local database.
 * This entity stores various types of health metrics retrieved from Health Connect.
 *
 * @property id Unique identifier for the cache entry, auto-generated by Room.
 * @property type The type of health data (e.g., "STEPS", "HEART_RATE", "CALORIES", "EXERCISE").
 * @property value The numerical value of the metric (e.g., step count or heart rate in bpm).
 * @property startTime The start timestamp of the data interval in epoch milliseconds.
 * @property endTime The end timestamp of the data interval in epoch milliseconds.
 * @property sourceApp The package name of the application that originally provided the data.
 * @property metadata Optional additional information or notes associated with the data entry.
 */
@Entity(tableName = "health_cache")
data class HealthCacheEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    val type: String,
    val value: Double,
    val startTime: Long,
    val endTime: Long,
    val sourceApp: String,
    val metadata: String? = null
)
